package: spreadsheet_export
version: '0.0.1-dev'
author: 'Alexander Walther'
supportpage: https://github.com/alexplusde/spreadsheet_export


requires:
    php:
        version: '>7.4,<9'
    redaxo: ^5.13
    packages:
        yform: "^4"

page:
    hidden: true

#pages:
#    spreadsheet_export:
#        title: translate:spreadsheet_export_title#
#
#        block: system
#        prio: 15
#        icon: rex-icon fa-calendar
#        perm: spreadsheet_export[]
#

installer_ignore:
  - .git
  - .github
  - node_modules
  - tests
  - tests_output
  - .editorconfig
  - .eslintrc.js
  - .gitignore
  - .stylelintrc.js
  - composer.json
  - composer.lock
  - nightwatch.conf.js
  - package.json
  - package-lock.json
  - yarn.lock
  - phpcs.xml
  - phpunit.xml
  - resources
  - .php-cs-fixer.dist.php
