package: spreadsheet_export
version: '1.0.0'
author: 'Alexander Walther'
supportpage: https://github.com/alexplusde/spreadsheet_export


requires:
    php:
        version: '>7.4,<9'
    redaxo: ^5.13
    packages:
        yform: "^4"

page:
    hidden: true

installer_ignore:
  - .git
  - .github
